/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppYamlRouteImport } from './routes/_app.yaml'
import { Route as AppVolumesRouteImport } from './routes/_app.volumes'
import { Route as AppStacksRouteImport } from './routes/_app.stacks'
import { Route as AppSetupRouteImport } from './routes/_app.setup'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRegistryRouteImport } from './routes/_app.registry'
import { Route as AppMetricsRouteImport } from './routes/_app.metrics'
import { Route as AppImagesRouteImport } from './routes/_app.images'
import { Route as AppEnvRouteImport } from './routes/_app.env'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContainersRouteImport } from './routes/_app.containers'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppStacksStackIdRouteImport } from './routes/_app.stacks.$stackId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYamlRoute = AppYamlRouteImport.update({
  id: '/yaml',
  path: '/yaml',
  getParentRoute: () => AppRoute,
} as any)
const AppVolumesRoute = AppVolumesRouteImport.update({
  id: '/volumes',
  path: '/volumes',
  getParentRoute: () => AppRoute,
} as any)
const AppStacksRoute = AppStacksRouteImport.update({
  id: '/stacks',
  path: '/stacks',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryRoute = AppRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppImagesRoute = AppImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvRoute = AppEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContainersRoute = AppContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppStacksStackIdRoute = AppStacksStackIdRouteImport.update({
  id: '/$stackId',
  path: '/$stackId',
  getParentRoute: () => AppStacksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/containers': typeof AppContainersRoute
  '/dashboard': typeof AppDashboardRoute
  '/env': typeof AppEnvRoute
  '/images': typeof AppImagesRoute
  '/metrics': typeof AppMetricsRoute
  '/registry': typeof AppRegistryRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/stacks': typeof AppStacksRouteWithChildren
  '/volumes': typeof AppVolumesRoute
  '/yaml': typeof AppYamlRoute
  '/stacks/$stackId': typeof AppStacksStackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/containers': typeof AppContainersRoute
  '/dashboard': typeof AppDashboardRoute
  '/env': typeof AppEnvRoute
  '/images': typeof AppImagesRoute
  '/metrics': typeof AppMetricsRoute
  '/registry': typeof AppRegistryRoute
  '/settings': typeof AppSettingsRoute
  '/setup': typeof AppSetupRoute
  '/stacks': typeof AppStacksRouteWithChildren
  '/volumes': typeof AppVolumesRoute
  '/yaml': typeof AppYamlRoute
  '/stacks/$stackId': typeof AppStacksStackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/database': typeof DatabaseRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/containers': typeof AppContainersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/env': typeof AppEnvRoute
  '/_app/images': typeof AppImagesRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/registry': typeof AppRegistryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/stacks': typeof AppStacksRouteWithChildren
  '/_app/volumes': typeof AppVolumesRoute
  '/_app/yaml': typeof AppYamlRoute
  '/_app/stacks/$stackId': typeof AppStacksStackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/database'
    | '/onboarding'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/containers'
    | '/dashboard'
    | '/env'
    | '/images'
    | '/metrics'
    | '/registry'
    | '/settings'
    | '/setup'
    | '/stacks'
    | '/volumes'
    | '/yaml'
    | '/stacks/$stackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/database'
    | '/onboarding'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/containers'
    | '/dashboard'
    | '/env'
    | '/images'
    | '/metrics'
    | '/registry'
    | '/settings'
    | '/setup'
    | '/stacks'
    | '/volumes'
    | '/yaml'
    | '/stacks/$stackId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/database'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_app/ai'
    | '/_app/alerts'
    | '/_app/containers'
    | '/_app/dashboard'
    | '/_app/env'
    | '/_app/images'
    | '/_app/metrics'
    | '/_app/registry'
    | '/_app/settings'
    | '/_app/setup'
    | '/_app/stacks'
    | '/_app/volumes'
    | '/_app/yaml'
    | '/_app/stacks/$stackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DatabaseRoute: typeof DatabaseRoute
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/yaml': {
      id: '/_app/yaml'
      path: '/yaml'
      fullPath: '/yaml'
      preLoaderRoute: typeof AppYamlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/volumes': {
      id: '/_app/volumes'
      path: '/volumes'
      fullPath: '/volumes'
      preLoaderRoute: typeof AppVolumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stacks': {
      id: '/_app/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof AppStacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registry': {
      id: '/_app/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AppRegistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/images': {
      id: '/_app/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AppImagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/env': {
      id: '/_app/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof AppEnvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/containers': {
      id: '/_app/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof AppContainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stacks/$stackId': {
      id: '/_app/stacks/$stackId'
      path: '/$stackId'
      fullPath: '/stacks/$stackId'
      preLoaderRoute: typeof AppStacksStackIdRouteImport
      parentRoute: typeof AppStacksRoute
    }
  }
}

interface AppStacksRouteChildren {
  AppStacksStackIdRoute: typeof AppStacksStackIdRoute
}

const AppStacksRouteChildren: AppStacksRouteChildren = {
  AppStacksStackIdRoute: AppStacksStackIdRoute,
}

const AppStacksRouteWithChildren = AppStacksRoute._addFileChildren(
  AppStacksRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppContainersRoute: typeof AppContainersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEnvRoute: typeof AppEnvRoute
  AppImagesRoute: typeof AppImagesRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppRegistryRoute: typeof AppRegistryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppStacksRoute: typeof AppStacksRouteWithChildren
  AppVolumesRoute: typeof AppVolumesRoute
  AppYamlRoute: typeof AppYamlRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppContainersRoute: AppContainersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEnvRoute: AppEnvRoute,
  AppImagesRoute: AppImagesRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppRegistryRoute: AppRegistryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppStacksRoute: AppStacksRouteWithChildren,
  AppVolumesRoute: AppVolumesRoute,
  AppYamlRoute: AppYamlRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DatabaseRoute: DatabaseRoute,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
