/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppYamlRouteImport } from './routes/_app.yaml'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppStacksRouteImport } from './routes/_app.stacks'
import { Route as AppSnippetsRouteImport } from './routes/_app.snippets'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRegistryRouteImport } from './routes/_app.registry'
import { Route as AppNetworkRouteImport } from './routes/_app.network'
import { Route as AppMetricsRouteImport } from './routes/_app.metrics'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppEnvRouteImport } from './routes/_app.env'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContainersRouteImport } from './routes/_app.containers'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppStacksStackIdRouteImport } from './routes/_app.stacks.$stackId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYamlRoute = AppYamlRouteImport.update({
  id: '/yaml',
  path: '/yaml',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppStacksRoute = AppStacksRouteImport.update({
  id: '/stacks',
  path: '/stacks',
  getParentRoute: () => AppRoute,
} as any)
const AppSnippetsRoute = AppSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistryRoute = AppRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppEnvRoute = AppEnvRouteImport.update({
  id: '/env',
  path: '/env',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContainersRoute = AppContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppStacksStackIdRoute = AppStacksStackIdRouteImport.update({
  id: '/$stackId',
  path: '/$stackId',
  getParentRoute: () => AppStacksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/containers': typeof AppContainersRoute
  '/dashboard': typeof AppDashboardRoute
  '/env': typeof AppEnvRoute
  '/logs': typeof AppLogsRoute
  '/metrics': typeof AppMetricsRoute
  '/network': typeof AppNetworkRoute
  '/registry': typeof AppRegistryRoute
  '/settings': typeof AppSettingsRoute
  '/snippets': typeof AppSnippetsRoute
  '/stacks': typeof AppStacksRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/yaml': typeof AppYamlRoute
  '/stacks/$stackId': typeof AppStacksStackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ai': typeof AppAiRoute
  '/alerts': typeof AppAlertsRoute
  '/containers': typeof AppContainersRoute
  '/dashboard': typeof AppDashboardRoute
  '/env': typeof AppEnvRoute
  '/logs': typeof AppLogsRoute
  '/metrics': typeof AppMetricsRoute
  '/network': typeof AppNetworkRoute
  '/registry': typeof AppRegistryRoute
  '/settings': typeof AppSettingsRoute
  '/snippets': typeof AppSnippetsRoute
  '/stacks': typeof AppStacksRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/yaml': typeof AppYamlRoute
  '/stacks/$stackId': typeof AppStacksStackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/containers': typeof AppContainersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/env': typeof AppEnvRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/network': typeof AppNetworkRoute
  '/_app/registry': typeof AppRegistryRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/snippets': typeof AppSnippetsRoute
  '/_app/stacks': typeof AppStacksRouteWithChildren
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/yaml': typeof AppYamlRoute
  '/_app/stacks/$stackId': typeof AppStacksStackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/containers'
    | '/dashboard'
    | '/env'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/registry'
    | '/settings'
    | '/snippets'
    | '/stacks'
    | '/templates'
    | '/yaml'
    | '/stacks/$stackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/sitemap.xml'
    | '/ai'
    | '/alerts'
    | '/containers'
    | '/dashboard'
    | '/env'
    | '/logs'
    | '/metrics'
    | '/network'
    | '/registry'
    | '/settings'
    | '/snippets'
    | '/stacks'
    | '/templates'
    | '/yaml'
    | '/stacks/$stackId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/sitemap.xml'
    | '/_app/ai'
    | '/_app/alerts'
    | '/_app/containers'
    | '/_app/dashboard'
    | '/_app/env'
    | '/_app/logs'
    | '/_app/metrics'
    | '/_app/network'
    | '/_app/registry'
    | '/_app/settings'
    | '/_app/snippets'
    | '/_app/stacks'
    | '/_app/templates'
    | '/_app/yaml'
    | '/_app/stacks/$stackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/yaml': {
      id: '/_app/yaml'
      path: '/yaml'
      fullPath: '/yaml'
      preLoaderRoute: typeof AppYamlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stacks': {
      id: '/_app/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof AppStacksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snippets': {
      id: '/_app/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AppSnippetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registry': {
      id: '/_app/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AppRegistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/network': {
      id: '/_app/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/env': {
      id: '/_app/env'
      path: '/env'
      fullPath: '/env'
      preLoaderRoute: typeof AppEnvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/containers': {
      id: '/_app/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof AppContainersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stacks/$stackId': {
      id: '/_app/stacks/$stackId'
      path: '/$stackId'
      fullPath: '/stacks/$stackId'
      preLoaderRoute: typeof AppStacksStackIdRouteImport
      parentRoute: typeof AppStacksRoute
    }
  }
}

interface AppStacksRouteChildren {
  AppStacksStackIdRoute: typeof AppStacksStackIdRoute
}

const AppStacksRouteChildren: AppStacksRouteChildren = {
  AppStacksStackIdRoute: AppStacksStackIdRoute,
}

const AppStacksRouteWithChildren = AppStacksRoute._addFileChildren(
  AppStacksRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppContainersRoute: typeof AppContainersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEnvRoute: typeof AppEnvRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppNetworkRoute: typeof AppNetworkRoute
  AppRegistryRoute: typeof AppRegistryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSnippetsRoute: typeof AppSnippetsRoute
  AppStacksRoute: typeof AppStacksRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppYamlRoute: typeof AppYamlRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppContainersRoute: AppContainersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEnvRoute: AppEnvRoute,
  AppLogsRoute: AppLogsRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppNetworkRoute: AppNetworkRoute,
  AppRegistryRoute: AppRegistryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSnippetsRoute: AppSnippetsRoute,
  AppStacksRoute: AppStacksRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppYamlRoute: AppYamlRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
